# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'weekly'
    versioning-strategy: increase
    assignees:
      - 'dominik-juriga'
    commit-message:
      include: scope
      prefix: 'chore:'
    labels:
      - 'pr: chore'
    ignore:
      - dependency-name: "@strapi/*"
        # Ignore versions of Strapi that are equal to or greater than 5.4.0
        # Updating to the latest versions breaks backwards compatibility
        # Using older deps works with newer versions of Strapi, but not the other way around
        versions: [ ">=5.4.1" ]